[package]
name = "worker"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "worker"
path = "src/main.rs"

[dependencies]
config = { path = "../../crates/config" }
engine = { path = "../../crates/engine" }
tokio = { version = "1.52.3", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
