[workspace]
resolver = "2"
members = [
    "crates/accounts",
    "crates/common",
    "crates/decoder",
    "crates/engine",
    "crates/execution",
    "crates/graph",
    "crates/pricing",
    "crates/risk",
    "crates/risk_engine",
    "crates/position",
    "crates/routing",
    "crates/rpc_client",
    "crates/stream",
]

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT"

[workspace.dependencies]
thiserror = "2"
