[package]
name = "stream"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
common.workspace = true
crossbeam-channel.workspace = true
dashmap.workspace = true
rpc_client.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
