[package]
name = "execution"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
base64 = "0.22"
bs58 = "0.5"
common = { path = "../common" }
config = { path = "../config" }
graph = { version = "0.1.0", path = "../graph" }
pricing = { path = "../pricing" }
routing = { path = "../routing" }
wallet = { path = "../wallet" }
crossbeam-channel = "0.5"
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1.52.3", features = ["rt", "rt-multi-thread", "macros"] }
tracing = "0.1.44"
