'use client';

// Trades are generated by the paper trading engine (not yet wired).
// This page shows a placeholder table that will populate once the
// TradeEvent WebSocket event is flowing.

import { useWsEvents } from '@/lib/hooks';

interface TradeEvent {
  trade_id:      string;
  timestamp_us:  number;
  pool_address:  string;
  direction:     string;
  amount_usd:    number;
  pnl_usd:       number;
  signal_id:     number;
}

export default function TradesPage() {
  // Subscribe to trade events from the WebSocket stream.
  // Cast to any since TradeEvent isn't in the types union yet.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const rawTrades = useWsEvents('status' as any, 1000) as unknown as TradeEvent[];
  const trades: TradeEvent[] = Array.isArray(rawTrades) ? [] : [];

  return (
    <div className="space-y-5 max-w-6xl">
      <div>
        <h1 className="text-xl font-semibold text-slate-100">Trades</h1>
        <p className="text-slate-400 text-sm mt-0.5">
          Paper trading execution history (live once engine is active)
        </p>
      </div>

      <div className="bg-slate-800 border border-slate-700 rounded-xl overflow-hidden">
        <table className="w-full text-sm">
          <thead className="border-b border-slate-700">
            <tr className="text-slate-400 text-xs uppercase tracking-wide">
              <th className="text-left px-4 py-3">Time</th>
              <th className="text-left px-4 py-3">Pool</th>
              <th className="text-left px-4 py-3">Direction</th>
              <th className="text-right px-4 py-3">Amount</th>
              <th className="text-right px-4 py-3">PnL</th>
              <th className="text-right px-4 py-3">Signal</th>
            </tr>
          </thead>
          <tbody>
            {trades.length === 0 ? (
              <tr>
                <td colSpan={6} className="text-center py-16 text-slate-500">
                  No trades yet — start the paper trading engine.
                </td>
              </tr>
            ) : (
              trades.map((t, i) => (
                <tr key={i} className="border-t border-slate-700/50 hover:bg-slate-700/20">
                  <td className="px-4 py-3 text-slate-400 mono text-xs">
                    {new Date(t.timestamp_us / 1000).toLocaleTimeString()}
                  </td>
                  <td className="px-4 py-3 mono text-xs truncate max-w-[120px] text-slate-300">
                    {t.pool_address.slice(0, 12)}…
                  </td>
                  <td className="px-4 py-3">
                    <span className={`text-xs px-2 py-0.5 rounded font-medium ${
                      t.direction === 'Long' ? 'bg-green-500/15 text-green-400' :
                      t.direction === 'Short' ? 'bg-red-500/15 text-red-400' :
                      'bg-slate-700 text-slate-400'
                    }`}>
                      {t.direction}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-right mono text-slate-300">
                    ${t.amount_usd.toFixed(2)}
                  </td>
                  <td className={`px-4 py-3 text-right mono font-medium ${
                    t.pnl_usd >= 0 ? 'text-green-400' : 'text-red-400'
                  }`}>
                    {t.pnl_usd >= 0 ? '+' : ''}${t.pnl_usd.toFixed(2)}
                  </td>
                  <td className="px-4 py-3 text-right mono text-slate-500 text-xs">
                    #{t.signal_id}
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
