[package]
name = "pricing"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
common = { path = "../common" }
config = { path = "../config" }
decoder = { path = "../decoder" }
events = { path = "../events" }
ratelimit = { path = "../ratelimit" }
reqwest = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
bs58 = "0.5"
