[package]
name = "ingestion"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
common = { path = "../common" }
config = { path = "../config" }
events = { path = "../events" }
tokio = { workspace = true }
tokio-tungstenite = "0.24"
futures-util = "0.3"
serde_json = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
