[package]
name = "orchestrator"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
config            = { path = "../config" }
common            = { path = "../common" }
signals           = { path = "../signals" }
crossbeam-channel = "0.5"
tokio             = { workspace = true }
tracing           = { workspace = true }
thiserror         = { workspace = true }
serde             = { workspace = true }
serde_json        = { workspace = true }
